# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'automarryUI.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(440, 130, 311, 235))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.REFRESHpushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.REFRESHpushButton.setObjectName("REFRESHpushButton")
        self.gridLayout.addWidget(self.REFRESHpushButton, 4, 0, 1, 1)
        self.CONNECTpushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CONNECTpushButton.setObjectName("CONNECTpushButton")
        self.gridLayout.addWidget(self.CONNECTpushButton, 3, 0, 1, 1)
        self.PORTlistWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.PORTlistWidget.setObjectName("PORTlistWidget")
        self.gridLayout.addWidget(self.PORTlistWidget, 1, 0, 1, 1)
        self.RATElistWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.RATElistWidget.setObjectName("RATElistWidget")
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.RATElistWidget.addItem(item)
        self.gridLayout.addWidget(self.RATElistWidget, 2, 0, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 10, 731, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.PHtextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.PHtextBrowser.setObjectName("PHtextBrowser")
        self.horizontalLayout_3.addWidget(self.PHtextBrowser)
        self.SUBSTRATtextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.SUBSTRATtextBrowser.setObjectName("SUBSTRATtextBrowser")
        self.horizontalLayout_3.addWidget(self.SUBSTRATtextBrowser)
        self.LEVEL_TOPtextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.LEVEL_TOPtextBrowser.setObjectName("LEVEL_TOPtextBrowser")
        self.horizontalLayout_3.addWidget(self.LEVEL_TOPtextBrowser)
        self.LEVEL_BOTtextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.LEVEL_BOTtextBrowser.setObjectName("LEVEL_BOTtextBrowser")
        self.horizontalLayout_3.addWidget(self.LEVEL_BOTtextBrowser)
        self.TANK_STATEtextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.TANK_STATEtextBrowser.setObjectName("TANK_STATEtextBrowser")
        self.horizontalLayout_3.addWidget(self.TANK_STATEtextBrowser)
        self.TIMEtextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.TIMEtextBrowser.setObjectName("TIMEtextBrowser")
        self.horizontalLayout_3.addWidget(self.TIMEtextBrowser)
        self.PERIODtextBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.PERIODtextBrowser.setObjectName("PERIODtextBrowser")
        self.horizontalLayout_3.addWidget(self.PERIODtextBrowser)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 110, 371, 494))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LVL_LlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.LVL_LlineEdit.setObjectName("LVL_LlineEdit")
        self.gridLayout_2.addWidget(self.LVL_LlineEdit, 2, 0, 1, 1)
        self.PH_DELAYlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.PH_DELAYlineEdit.setObjectName("PH_DELAYlineEdit")
        self.gridLayout_2.addWidget(self.PH_DELAYlineEdit, 9, 0, 1, 1)
        self.PH_MINUS_DOZElabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PH_MINUS_DOZElabel.setObjectName("PH_MINUS_DOZElabel")
        self.gridLayout_2.addWidget(self.PH_MINUS_DOZElabel, 6, 1, 1, 1)
        self.LVL_HpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.LVL_HpushButton.setObjectName("LVL_HpushButton")
        self.gridLayout_2.addWidget(self.LVL_HpushButton, 1, 2, 1, 1)
        self.PH_MAXlabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PH_MAXlabel.setObjectName("PH_MAXlabel")
        self.gridLayout_2.addWidget(self.PH_MAXlabel, 3, 1, 1, 1)
        self.FERT_DOZEpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.FERT_DOZEpushButton.setObjectName("FERT_DOZEpushButton")
        self.gridLayout_2.addWidget(self.FERT_DOZEpushButton, 7, 2, 1, 1)
        self.PH_PLUS_DOZElabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PH_PLUS_DOZElabel.setObjectName("PH_PLUS_DOZElabel")
        self.gridLayout_2.addWidget(self.PH_PLUS_DOZElabel, 5, 1, 1, 1)
        self.PRE_DELAYlabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PRE_DELAYlabel.setObjectName("PRE_DELAYlabel")
        self.gridLayout_2.addWidget(self.PRE_DELAYlabel, 0, 1, 1, 1)
        self.PH_MAXlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.PH_MAXlineEdit.setObjectName("PH_MAXlineEdit")
        self.gridLayout_2.addWidget(self.PH_MAXlineEdit, 3, 0, 1, 1)
        self.SUBST_HUMlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.SUBST_HUMlineEdit.setObjectName("SUBST_HUMlineEdit")
        self.gridLayout_2.addWidget(self.SUBST_HUMlineEdit, 8, 0, 1, 1)
        self.PH_DELAYlabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PH_DELAYlabel.setObjectName("PH_DELAYlabel")
        self.gridLayout_2.addWidget(self.PH_DELAYlabel, 9, 1, 1, 1)
        self.PH_DELAYpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.PH_DELAYpushButton.setObjectName("PH_DELAYpushButton")
        self.gridLayout_2.addWidget(self.PH_DELAYpushButton, 9, 2, 1, 1)
        self.PREDELAYlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.PREDELAYlineEdit.setObjectName("PREDELAYlineEdit")
        self.gridLayout_2.addWidget(self.PREDELAYlineEdit, 0, 0, 1, 1)
        self.LVL_Hlabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LVL_Hlabel.setObjectName("LVL_Hlabel")
        self.gridLayout_2.addWidget(self.LVL_Hlabel, 1, 1, 1, 1)
        self.LVL_LpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.LVL_LpushButton.setObjectName("LVL_LpushButton")
        self.gridLayout_2.addWidget(self.LVL_LpushButton, 2, 2, 1, 1)
        self.SUBST_HUMlabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.SUBST_HUMlabel.setObjectName("SUBST_HUMlabel")
        self.gridLayout_2.addWidget(self.SUBST_HUMlabel, 8, 1, 1, 1)
        self.PH_MINUS_DOZElineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.PH_MINUS_DOZElineEdit.setObjectName("PH_MINUS_DOZElineEdit")
        self.gridLayout_2.addWidget(self.PH_MINUS_DOZElineEdit, 6, 0, 1, 1)
        self.PH_PLUS_DOZElineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.PH_PLUS_DOZElineEdit.setObjectName("PH_PLUS_DOZElineEdit")
        self.gridLayout_2.addWidget(self.PH_PLUS_DOZElineEdit, 5, 0, 1, 1)
        self.PH_MINUS_DOZEpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.PH_MINUS_DOZEpushButton.setObjectName("PH_MINUS_DOZEpushButton")
        self.gridLayout_2.addWidget(self.PH_MINUS_DOZEpushButton, 6, 2, 1, 1)
        self.PH_PLUS_DOZEpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.PH_PLUS_DOZEpushButton.setObjectName("PH_PLUS_DOZEpushButton")
        self.gridLayout_2.addWidget(self.PH_PLUS_DOZEpushButton, 5, 2, 1, 1)
        self.PH_MINlineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.PH_MINlineEdit.setObjectName("PH_MINlineEdit")
        self.gridLayout_2.addWidget(self.PH_MINlineEdit, 4, 0, 1, 1)
        self.FERT_DOZElineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.FERT_DOZElineEdit.setObjectName("FERT_DOZElineEdit")
        self.gridLayout_2.addWidget(self.FERT_DOZElineEdit, 7, 0, 1, 1)
        self.LVL_HEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.LVL_HEdit.setObjectName("LVL_HEdit")
        self.gridLayout_2.addWidget(self.LVL_HEdit, 1, 0, 1, 1)
        self.FERT_DOZElabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.FERT_DOZElabel.setObjectName("FERT_DOZElabel")
        self.gridLayout_2.addWidget(self.FERT_DOZElabel, 7, 1, 1, 1)
        self.LVL_Llabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.LVL_Llabel.setObjectName("LVL_Llabel")
        self.gridLayout_2.addWidget(self.LVL_Llabel, 2, 1, 1, 1)
        self.PH_MAXpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.PH_MAXpushButton.setObjectName("PH_MAXpushButton")
        self.gridLayout_2.addWidget(self.PH_MAXpushButton, 3, 2, 1, 1)
        self.PH_MINpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.PH_MINpushButton.setObjectName("PH_MINpushButton")
        self.gridLayout_2.addWidget(self.PH_MINpushButton, 4, 2, 1, 1)
        self.SUBST_HUMpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.SUBST_HUMpushButton.setObjectName("SUBST_HUMpushButton")
        self.gridLayout_2.addWidget(self.SUBST_HUMpushButton, 8, 2, 1, 1)
        self.PH_MINlabel = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.PH_MINlabel.setObjectName("PH_MINlabel")
        self.gridLayout_2.addWidget(self.PH_MINlabel, 4, 1, 1, 1)
        self.PRE_DELAYpushButton = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.PRE_DELAYpushButton.setObjectName("PRE_DELAYpushButton")
        self.gridLayout_2.addWidget(self.PRE_DELAYpushButton, 0, 2, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(440, 390, 231, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.PH_PLUScheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.PH_PLUScheckBox.setObjectName("PH_PLUScheckBox")
        self.verticalLayout.addWidget(self.PH_PLUScheckBox)
        self.PH_MINUScheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.PH_MINUScheckBox.setObjectName("PH_MINUScheckBox")
        self.verticalLayout.addWidget(self.PH_MINUScheckBox)
        self.CLR_WTRcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.CLR_WTRcheckBox.setObjectName("CLR_WTRcheckBox")
        self.verticalLayout.addWidget(self.CLR_WTRcheckBox)
        self.FERT_WTRcheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        self.FERT_WTRcheckBox.setObjectName("FERT_WTRcheckBox")
        self.verticalLayout.addWidget(self.FERT_WTRcheckBox)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 60, 31, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(160, 60, 71, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 60, 71, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(370, 60, 71, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(470, 60, 91, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(600, 60, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(700, 60, 60, 16))
        self.label_7.setObjectName("label_7")
        self.TESTpushButton = QtWidgets.QPushButton(self.centralwidget)
        self.TESTpushButton.setGeometry(QtCore.QRect(460, 540, 113, 32))
        self.TESTpushButton.setObjectName("TESTpushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.REFRESHpushButton.setText(_translate("MainWindow", "refresh"))
        self.CONNECTpushButton.setText(_translate("MainWindow", "connect"))
        __sortingEnabled = self.RATElistWidget.isSortingEnabled()
        self.RATElistWidget.setSortingEnabled(False)
        item = self.RATElistWidget.item(0)
        item.setText(_translate("MainWindow", "115200"))
        item = self.RATElistWidget.item(1)
        item.setText(_translate("MainWindow", "57600"))
        item = self.RATElistWidget.item(2)
        item.setText(_translate("MainWindow", "38400"))
        item = self.RATElistWidget.item(3)
        item.setText(_translate("MainWindow", "9600"))
        self.RATElistWidget.setSortingEnabled(__sortingEnabled)
        self.PH_MINUS_DOZElabel.setText(_translate("MainWindow", "TextLabel"))
        self.LVL_HpushButton.setText(_translate("MainWindow", "LVL_H"))
        self.PH_MAXlabel.setText(_translate("MainWindow", "TextLabel"))
        self.FERT_DOZEpushButton.setText(_translate("MainWindow", "FERT_DOZE"))
        self.PH_PLUS_DOZElabel.setText(_translate("MainWindow", "TextLabel"))
        self.PRE_DELAYlabel.setText(_translate("MainWindow", "TextLabel"))
        self.PH_DELAYlabel.setText(_translate("MainWindow", "TextLabel"))
        self.PH_DELAYpushButton.setText(_translate("MainWindow", "PH_DELAY"))
        self.LVL_Hlabel.setText(_translate("MainWindow", "TextLabel"))
        self.LVL_LpushButton.setText(_translate("MainWindow", "LVL_L"))
        self.SUBST_HUMlabel.setText(_translate("MainWindow", "TextLabel"))
        self.PH_MINUS_DOZEpushButton.setText(_translate("MainWindow", "PH_MINUS_DOZE"))
        self.PH_PLUS_DOZEpushButton.setText(_translate("MainWindow", "PH_PLUS_DOZE"))
        self.FERT_DOZElabel.setText(_translate("MainWindow", "TextLabel"))
        self.LVL_Llabel.setText(_translate("MainWindow", "TextLabel"))
        self.PH_MAXpushButton.setText(_translate("MainWindow", "PH_MAX"))
        self.PH_MINpushButton.setText(_translate("MainWindow", "PH_MIN"))
        self.SUBST_HUMpushButton.setText(_translate("MainWindow", "SUBST_HUM"))
        self.PH_MINlabel.setText(_translate("MainWindow", "TextLabel"))
        self.PRE_DELAYpushButton.setText(_translate("MainWindow", "PRE_DEL"))
        self.PH_PLUScheckBox.setText(_translate("MainWindow", "ph plus pump"))
        self.PH_MINUScheckBox.setText(_translate("MainWindow", "ph minus pump"))
        self.CLR_WTRcheckBox.setText(_translate("MainWindow", "clear wtr pump"))
        self.FERT_WTRcheckBox.setText(_translate("MainWindow", "fert wtr pump"))
        self.label.setText(_translate("MainWindow", "PH"))
        self.label_2.setText(_translate("MainWindow", "SUBSTRAT"))
        self.label_3.setText(_translate("MainWindow", "LEVEL TOP"))
        self.label_4.setText(_translate("MainWindow", "LEVEL BOT"))
        self.label_5.setText(_translate("MainWindow", "TANK STATE"))
        self.label_6.setText(_translate("MainWindow", "TIME"))
        self.label_7.setText(_translate("MainWindow", "PERIOD"))
        self.TESTpushButton.setText(_translate("MainWindow", "TEST"))

